### ISSUE TITLE
Discuss: Add function in core: executeWithoutReward()

### ISSUE THREAD

**Issue by hilmarx** [gelatofinance/gelato#116]

**Comment by hilmarx** [comment]
@gitpusha how about instead of asking interfaces to write manual withdraw functions for every function (out of security purposes), we provide users with a backdoor in the gelatoCore contract, that IF an interface goes bankrupt and the users funds are 'stuck' as the interfaces balance is insufficient on gelatoCore, offers users a way to still execute the transaction on their own cost, calling the pre selected action & triggers and receiving back ones tokens in the worst case.

This is of course only necessary if interfaces apply our current strategy of pre charging the users ERC20 tokens instead of only approving them for the action (which should be the best practice imo). Still a function that enables users to execute 'stuck' execution Claims based on paying the costs themselves might still be worth it for some edge cases. We can also open up the function so everyone can call it, potentially enabling interfaces that somehow fucked up to execute executable execution claims on behalf of minted users.

**Comment by gitpusha** [comment]
This is basically what I suggested a while back:
We build a simple `UI` component (the `execute button`) - user's can then play `executors` via a `GUI`. 
I think this is inelegant but it is an edge case solution.
I would not bake it into our first versions, and keep it in our pockets till later.

**Comment by hilmarx** [comment]
yes, this is deprecated. Discussion about the actual problem (insufficinet aggregator balance) goes into #122
