### ISSUE TITLE
Modularize gelato core and DutchX postSellOrder logic

### ISSUE THREAD

**Issue by hilmarx** [gelatofinance/gelato#21]

**Comment by bytezantium** [comment]
![gelato-modular-architecture](https://user-images.githubusercontent.com/36712489/60448344-b1124b80-9c25-11e9-8b54-ffcccef171a2.jpg)

**Comment by hilmarx** [comment]
Implement feature to make withdraw optional by:

1) Create state variable to ask if automatically withdrawable or not
2) If yes, charge the user bounty `payments == subOrderAmount +1`
3) Make the automatic withdrawals optional
4) Create separate function that conducts the last withdraw for a given `SellOrder` using the `iHash`, given that `remainingWithdraws == 1 and SubOrderAmount == 0`

**Comment by bytezantium** [comment]
this was done with #37 in mind

**Comment by bytezantium** [comment]
merged in #43

**Comment by hilmarx** [comment]
Closed.
