### ISSUE TITLE
Devise GelatoPrepayment Formula

### ISSUE THREAD

**Issue by gitpusha** [gelatofinance/gelato#36]
The crux will be to come up with a way in which we can most effectively predict future gas prices at execution time.  The outcome should be a Gelato Prepaid Fee Formula (fees paid by end user) that allows us to operate our Execution Node Service (centralised) on a NET-BreakEven.

**Comment by bytezantium** [comment]
[Gelato-Prepayment-Formula.pdf](https://github.com/gelatofinance/gelato/files/3372902/Gelato-Prepayment-Formula.pdf)

**Comment by bytezantium** [comment]
![Gelato-Prepayment-Formula](https://user-images.githubusercontent.com/36712489/60887691-42507600-a255-11e9-9720-afe05f6703aa.png)
