### ISSUE TITLE
Evaluate Futures Trading protocol specs

### ISSUE THREAD

**Issue by bytezantium** [gelatofinance/gelato#41]

**Comment by bytezantium** [comment]
![Futures-Gelato-Claim-Definition copy](https://user-images.githubusercontent.com/36712489/60908615-9a4ea300-a27c-11e9-864a-a9f5d4921f11.png)

**Comment by bytezantium** [comment]
![Futures-Lifecycle copy](https://user-images.githubusercontent.com/36712489/60908635-a63a6500-a27c-11e9-83e6-3f69c1cdf588.png)

**Comment by hilmarx** [comment]
Closed until further notice.
