### ISSUE TITLE
Smart Contract Permissionless Interface Redesign and Tests

### ISSUE THREAD

**Issue by gitpusha** [gelatofinance/gelato#63]
**Smart Contract Redesign** 

- Permissionless Interfaces
- Gas Used and Payout calculation at Execution Time
- On-chain gas price oracle ChainLink proposal
- Price condition proposal 

**Testing**
_Unit Tests:_

- Make sure all tests in Test/ directory can be run and succeed via `truffle test` command
- No unit test should depend on entry via other script

_Integration Tests_

- end-to-end testing with executor and seller payout logic, automated withdrawals, manual withdrawals, and order cancellation
- TestConfig File should be at root and all child scripts should inherit variables from it
--> entry point should not be a bash script. bash scripts should be spawned from inside node.js via child processes.
--> make all variables dynamic and inheritable from our TestConfig.js files

**Comment by hilmarx** [comment]
**Testing architecture:**

1) Create modular unit tests for each callable state changing function (mint, exec, withdraw, cancel)
2) Create Test.config file which the individual unit tests fetch their data from
3) Create integration truffle tests that deploy individual bash scripts and unit truffle test files to test the most common test scenarios.
