### ISSUE TITLE
Final Edits: Protect executor / interface from running out of gas on interface execute function

### ISSUE THREAD

**Issue by gitpusha** [gelatofinance/gelato#78]
- reintroduce interfaceGas state variable on gelato core

- use gasleft() to check that executor has forwarded the interfaceGas + the gasOverhead

- refactor core to always forward interfaceGas along with the execute call

- keep gas overhead in case of out of gas revert to protect the executor from out of gas reverts on interface function

**Comment by hilmarx** [comment]
Make Gas Overhead include max gas overhead of canExec + everything before and after gasleft() calcs

**Comment by hilmarx** [comment]
Set correct GasOverhead

**Comment by hilmarx** [comment]
including the maxGas value is actually a protection for the interface, not the executor. It forces executors to use a sufficiently high gasLimit when transacting in order to protect interfaces from having its .call revert, which will not revert the remaining transaction handling the executors payout.

**Comment by hilmarx** [comment]
Add return data decoding and validation of return value for internal tx in core

**Comment by hilmarx** [comment]
Difficulty with setting maxGas:

Each transaction will consume a different amount of gas, based on the state variables which are set or nullified by each transaction. We need to run simulation of various test scenarios and take the highest number possible + a buffer to ensure the tx will not revert without any mistake in the actual code

**Comment by hilmarx** [comment]
gasleft does not work for internal functions that you call. Do research and if you dont find anything, do gasleft at the beginning and at the end of every func and update tests to see if it works then

**Comment by hilmarx** [comment]
use gasleft() to check that executor has forwarded the interfaceGas + the gasOverhead

keep gas overhead in case of out of gas revert to protect the executor from out of gas reverts on interface function

**Comment by hilmarx** [comment]
=> gasLeft calcs for executor payout are correct

**Comment by hilmarx** [comment]
1) Calculate the approx gas costs of the various function calls for the interface protection in the `execute()` func
